      - name: Upload APK to Google Drive
        id: gdrive_upload
        run: |
          # Required env
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" > service-account.json

          pip3 install google-auth google-auth-httplib2 google-api-python-client

          # Run Python upload script
          python3 upload_to_drive.py
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}

      - name: Read APK URL
        id: read_url
        run: |
          APK_URL=$(cat apk_url.txt)
          echo "apk_url=$APK_URL" >> $GITHUB_OUTPUT
          echo "Download URL: $APK_URL"
